#!/usr/bin/env python3
"""Tech Digest Viewer — 轻量 Web 界面查看技术热点报告."""

import html
import http.server
import os
import re
import socketserver
import datetime

PORT = 8765
ROADMAP_PATH = os.path.expanduser(
    "~/.claude/projects/-home-charlie/memory/ideas-roadmap.md"
)

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Tech Digest</title>
<style>
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
  font-family: -apple-system, "SF Mono", "JetBrains Mono", monospace;
  background: #0d1117; color: #c9d1d9;
  padding: 1.5rem; max-width: 1100px; margin: 0 auto;
}}
h2 {{
  color: #58a6ff; font-size: 1.3rem;
  border-bottom: 1px solid #21262d; padding-bottom: 0.5rem;
  margin: 1.5rem 0 1rem;
}}
h3 {{
  color: #79c0ff; font-size: 1.05rem; margin: 1.2rem 0 0.6rem;
}}
table {{
  width: 100%; border-collapse: collapse; margin-bottom: 1rem;
  font-size: 0.85rem;
}}
th {{
  background: #161b22; color: #8b949e; text-align: left;
  padding: 8px 10px; border-bottom: 2px solid #30363d;
  position: sticky; top: 0;
}}
td {{
  padding: 7px 10px; border-bottom: 1px solid #21262d;
  vertical-align: top; max-width: 400px; overflow: hidden;
  text-overflow: ellipsis; white-space: nowrap;
}}
tr:hover {{ background: #161b22; }}
a {{ color: #58a6ff; text-decoration: none; }}
a:hover {{ text-decoration: underline; }}
.badge {{
  display: inline-block; padding: 2px 8px; border-radius: 12px;
  font-size: 0.7rem; font-weight: 600; margin-left: 6px;
}}
.badge-lang {{ background: #1f6feb33; color: #58a6ff; }}
.badge-score {{ background: #238636; color: #3fb950; }}
.badge-date {{ background: #6e40c933; color: #bc8cff; }}
hr {{ border: none; border-top: 1px solid #21262d; margin: 2rem 0; }}
.header {{
  display: flex; justify-content: space-between; align-items: center;
  margin-bottom: 1rem;
}}
.header h1 {{ color: #f0f6fc; font-size: 1.5rem; }}
.meta {{ color: #8b949e; font-size: 0.8rem; }}
.stats {{
  display: flex; gap: 1rem; margin: 1rem 0;
}}
.stat-card {{
  background: #161b22; border: 1px solid #30363d; border-radius: 8px;
  padding: 0.8rem 1.2rem; flex: 1; text-align: center;
}}
.stat-card .num {{ font-size: 1.6rem; color: #58a6ff; font-weight: 700; }}
.stat-card .label {{ font-size: 0.75rem; color: #8b949e; margin-top: 2px; }}
.footer {{
  text-align: center; color: #484f58; font-size: 0.75rem;
  margin-top: 2rem; padding-top: 1rem;
  border-top: 1px solid #21262d;
}}
@media (max-width: 768px) {{
  body {{ padding: 0.8rem; }}
  td {{ max-width: 150px; font-size: 0.75rem; }}
  .stats {{ flex-direction: column; gap: 0.5rem; }}
}}
</style>
</head>
<body>
<div class="header">
  <h1>Tech Digest</h1>
  <div class="meta">
    Auto-generated weekly &middot;
    <a href="http://localhost:{port}/raw">Raw Markdown</a>
  </div>
</div>
<div class="stats">{stats}</div>
{content}
<div class="footer">
  Generated by ~/launcher/tech-digest.py &middot;
  systemd timer: tech-digest.timer &middot;
  Updated: {now}
</div>
</body>
</html>"""


def parse_markdown(md_text):
    """Parse ideas-roadmap.md into structured digest blocks."""
    blocks = []
    current = {"title": "", "sections": {}}
    current_section = None

    for line in md_text.split("\n"):
        # Digest title: ## Tech Digest — YYYY-MM-DD
        m = re.match(r"^## Tech Digest — (\d{4}-\d{2}-\d{2})", line)
        if m:
            if current["title"]:
                blocks.append(current)
            current = {"title": m.group(1), "sections": {}}
            current_section = None
            continue

        # Section title: ### GitHub Trending / arXiv / Hacker News
        m = re.match(r"^### (.+)", line)
        if m:
            current_section = m.group(1)
            current["sections"][current_section] = {"headers": [], "rows": []}
            continue

        # Table header
        if line.startswith("|") and current_section:
            cells = [c.strip() for c in line.strip("|").split("|")]
            if all(set(c) <= set("-") for c in cells if c):
                continue  # separator
            if not current["sections"][current_section]["headers"]:
                current["sections"][current_section]["headers"] = cells
            else:
                current["sections"][current_section]["rows"].append(cells)

    if current["title"]:
        blocks.append(current)
    return blocks


def render_table(headers, rows, section_name):
    """Render a table as HTML."""
    th_cells = "".join(f"<th>{html.escape(h)}</th>" for h in headers)
    html_parts = [f"<table><tr>{th_cells}</tr>"]

    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            cell = cell.strip()
            # Detect links: [text](url)
            link_match = re.match(r"^\[(.+?)\]\((.+?)\)$", cell)
            if link_match:
                text, url = link_match.group(1), link_match.group(2)
                inner = html.escape(text)
                cells.append(f'<td><a href="{html.escape(url)}" target="_blank">{inner}</a>')
            else:
                escaped = html.escape(cell)
                # Add badges for certain columns
                if headers[i] == "Lang" and cell and cell != "—":
                    escaped = f'<span class="badge badge-lang">{escaped}</span>'
                elif headers[i] == "Score" and cell.isdigit():
                    escaped = f'<span class="badge badge-score">★ {escaped}</span>'
                elif headers[i] == "Date" and re.match(r"\d{4}-", cell):
                    escaped = f'<span class="badge badge-date">{escaped}</span>'
                cells.append(f"<td>{escaped}")
        html_parts.append("<tr>" + "".join(cells) + "</tr>")

    html_parts.append("</table>")
    return "\n".join(html_parts)


def build_page(md_text, port=PORT):
    """Build full HTML page from markdown."""
    blocks = parse_markdown(md_text)
    if not blocks:
        return "<p>No digest data yet. Run tech-digest.py first.</p>"

    # Stats cards — count from latest digest
    latest = blocks[-1]
    stats_html = ""
    section_labels = {
        "GitHub Trending": "项目",
        "GitHub 热门项目": "项目",
        "arXiv Papers": "论文",
        "arXiv 论文": "论文",
        "Hacker News": "资讯",
    }
    for section_name, data in latest["sections"].items():
        count = len(data["rows"])
        label = section_labels.get(section_name, section_name)
        stats_html += (
            f'<div class="stat-card">'
            f'<div class="num">{count}</div>'
            f'<div class="label">{html.escape(label)}</div>'
            f'</div>'
        )

    # Content — show latest digest
    content_html = f'<h2>最新 — {html.escape(latest["title"])}</h2>\n'
    for section_name, data in latest["sections"].items():
        content_html += f"<h3>{html.escape(section_name)}</h3>\n"
        if data["headers"]:
            content_html += render_table(data["headers"], data["rows"], section_name)
        else:
            content_html += "<p>(no data)</p>"

    # History links
    if len(blocks) > 1:
        content_html += '<h2>历史记录</h2>\n<ul>\n'
        for b in reversed(blocks[:-1]):
            count = sum(len(s["rows"]) for s in b["sections"].values())
            content_html += (
                f'<li><a href="/digest/{b["title"]}">'
                f'{html.escape(b["title"])} ({count} items)</a></li>\n'
            )
        content_html += "</ul>\n"

    return PAGE_TEMPLATE.format(
        port=port,
        stats=stats_html,
        content=content_html,
        now=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
    )


class DigestHandler(http.server.BaseHTTPRequestHandler):
    """HTTP request handler for tech digest viewer."""

    def do_GET(self):
        if self.path == "/raw":
            self._serve_raw()
        elif self.path.startswith("/digest/"):
            date = self.path.split("/")[-1]
            self._serve_digest(date)
        elif self.path == "/" or self.path == "":
            self._serve_latest()
        else:
            self.send_error(404)

    def _read_md(self):
        try:
            with open(ROADMAP_PATH, "r", encoding="utf-8") as f:
                return f.read()
        except FileNotFoundError:
            return ""

    def _serve_latest(self):
        md = self._read_md()
        page = build_page(md, PORT)
        self._send_html(page)

    def _serve_digest(self, date):
        md = self._read_md()
        blocks = parse_markdown(md)
        target = None
        for b in blocks:
            if b["title"] == date:
                target = b
                break
        if not target:
            self.send_error(404, "Digest not found")
            return

        content = f"<h2>{html.escape(target['title'])}</h2>\n"
        for name, data in target["sections"].items():
            content += f"<h3>{html.escape(name)}</h3>\n"
            if data["headers"]:
                content += render_table(data["headers"], data["rows"], name)

        page = PAGE_TEMPLATE.format(
            port=PORT,
            stats="",
            content=content,
            now=datetime.datetime.now().strftime("%Y-%m-%d %H:%M"),
        )
        self._send_html(page)

    def _serve_raw(self):
        md = self._read_md()
        self.send_response(200)
        self.send_header("Content-Type", "text/markdown; charset=utf-8")
        self.end_headers()
        self.wfile.write(md.encode("utf-8"))

    def _send_html(self, page):
        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        self.wfile.write(page.encode("utf-8"))

    def log_message(self, fmt, *args):
        # Suppress request logs
        pass


def main():
    with socketserver.TCPServer(("", PORT), DigestHandler) as httpd:
        print(f"[OK] Tech Digest Viewer → http://localhost:{PORT}")
        httpd.serve_forever()


if __name__ == "__main__":
    main()
